export const configFile = [
  {
    name: 'hierarchy',
    property: 'select',
    value: ['None', 'ForDates', 'Interval', 'Ordering', 'Masking'],
    required: true,
    dependence: false,
  },
  {
    name: 'num',
    property: 'select',
    value: [
      "yyyy-MM-dd'T'HH:mm:ss'Z'",
      'yyyy-MM-ddZZ',
      "yyyy-MM-dd'T'HH:mm:ssz",
      "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
      'EEE MMM d hh:mm:ss z yyyy',
      'EEE MMM dd HH:mm:ss yyyy',
      'EEEE, dd-MMM-yy HH:mm:ss zzz',
      'EEE, dd MMM yyyy HH:mm:ss zzz',
      'EEE, dd MMM yy HH:mm:ss z',
      'EEE, dd MMM yy HH:mm z',
      'EEE, dd MMM yyyy HH:mm:ss z',
      "yyyy-MM-dd'T'HH:mm:ss",
      'EEE, dd MMM yyyy HH:mm:ss Z',
      'dd MMM yy HH:mm:ss z',
      'dd MMM yy HH:mm z',
      "'T'HH:mm:ss",
      "'T'HH:mm:ssZZ",
      'HH:mm:ss',
      'HH:mm:ssZZ',
      'yyyy-MM-dd',
      'yyyy-MM-dd hh:mm:ss',
      'yyyy-MM-dd HH:mm:ss',
      "yyyy-MM-dd'T'HH:mm:ssz",
      "yyyy-MM-dd'T'HH:mm:ss",
      "yyyy-MM-dd'T'HH:mm:ssZZ",
      'dd.MM.yyyy',
      'dd.MM.yyyy hh:mm:ss',
      'dd.MM.yyyy HH:mm:ss',
      "dd.MM.yyyy'T'HH:mm:ssz",
      "dd.MM.yyyy'T'HH:mm:ss",
      "dd.MM.yyyy'T'HH:mm:ssZZ",
      'dd.MM.yyyy hh:mm',
      'dd.MM.yyyy HH:mm',
      'dd/MM/yyyy',
      'dd/MM/yy',
      'MM/dd/yyyy',
      'MM/dd/yy',
      'MM/dd/yyyy hh:mm:ss',
      'MM/dd/yy hh:mm:ss',
    ],
    required: true,
    dependence: "hierarchy===ForDates",
  },
  {
    name: 'bottomSnamFrom',
    property: 'input',
    prompt:'请输入整数',
    limit: "[^\\d]",
    value: '',
    required: true,
    dependence: "hierarchy===Interval",
  },
  {
    name: 'bottomCodingFrom',
    property: 'input',
    prompt:'请输入整数',
    limit: "[^\\d]",
    value: '',
    required: true,
    dependence: "hierarchy===Interval",
  },
  {
    name: 'minFrom',
    property: 'input',
    prompt:'请输入整数',
    limit: "[^\\d]",
    value: '',
    required: true,
    dependence: "hierarchy===Interval",
  },
  {
    name: 'topSnampFrom',
    property: 'input',
    prompt:'请输入整数',
    limit: "[^\\d]",
    value: '',
    required: true,
    dependence: "hierarchy===Interval",
  },
  {
    name: 'topCodingFrom',
    property: 'input',
    value: '',
    prompt:'请输入整数',
    limit: "[^\\d]",
    required: true,
    dependence: "hierarchy===Interval",
  },
  {
    name: 'maxFrom',
    property: 'input',
    limit: "[^\\d]",
    prompt:'请输入整数',
    value: '',
    required: true,
    dependence: "hierarchy===Interval",
  },
  {
    name: 'orderDataType',
    property: 'select',
    value: ['Data', 'Decimal', 'Integer', 'String', 'Ordered String'],
    required: true,
    dependence: "hierarchy===Ordering",
  },
  {
    name: 'alignment',
    property: 'select',
    value: ['Right To Left', 'Left To Right'],
    required: true,
    dependence: "hierarchy===Masking",
  },
  {
    name: 'masking',
    property: 'select',
    value: ['Right To Left', 'Left To Right'],
    required: true,
    dependence: "hierarchy===Masking",
  },
  {
    name: 'dataType',
    property: 'select',
    value: ['Data', 'Decimal', 'Integer', 'String', 'Ordered', 'String'],
    required: true,
    dependence: false,
  },
  {
    name: 'isTargetVarible',
    property: 'select',
    value: [true, false],
    required: true,
    dependence: false,
  },
  {
    name: 'dataTransformationType',
    property: 'select',
    value: ['Insensitive', 'Sensitive', 'Quasi-identifying', 'Identifying'],
    required: true,
    dependence: false,
  },
  {
    name: 'transformation',
    property: 'select',
    value: [
      'Generalization',
      'Clustering and microaggregation',
      'MicroAggregation',
    ],
    required: true,
    dependence: false,
  },
  {
    name: 'minimum',
    property: 'input',
    limit: "[^\\d]",
    prompt:'请输入整数',
    value: '',
    required: true,
    dependence: 'transformation===Generalization',
  },
  {
    name: 'maximum',
    property: 'input',
    limit: "[^\\d]",
    prompt:'请输入整数',
    value: '',
    required: true,
    dependence: 'transformation===Generalization',
  },
  {
    name: 'functionName',
    property: 'select',
    value: [
      'Arithmetic mean',
      'Geometric mean',
      'Median',
      'Interval',
      'Mode',
      'Set',
    ],
    required: true,
    dependence: 'transformation===MicroAggregation',
  },
  {
    name: 'ClusteringfunctionName',
    property: 'select',
    value: [
      'Arithmetic mean',
      'Geometric mean',
      'Median',
      'Interval',
      'Mode',
      'Set',
    ],
    required: true,
    dependence: 'transformation===Clustering and microaggregation',
  },{
    name: 'weight',
    property: 'input',
    prompt:'请输入整数或者浮点数',
    limit: "[^\\d|\\.]",
    required: true,
    dependence:false
  }
];
