export const globalConfig = [
  {
    name: 'populationModel',
    property: 'select',
    value: [
      'None',
      'Africa',
      'Australia',
      'Europe',
      'NorthAmerica',
      'SouthAmerica',
      'EuropeUnion',
      'Brasil',
      'Canada',
      'China',
      'France',
      'Germany',
      'India',
      'UK',
      'USA',
    ],
    required: true,
    dependence: false,
  },
  {
    name: 'privacyModel',
    property: 'checkbox',
    value: [
      'DifferentPrivacy',
      'KAnonymity',
      'KMap',
      'Presence',
      'Profitability',
      'Diversity',
      'TCloseness',
      'Disclosure',
      'Likeness',
      'AverageReidentificationRisk',
      'PopulationUniqueness',
      'SampleUniqueness',
    ],
    required: false,
    dependence: false,
  },
  {
    name: 'delta',
    property: 'input',
    prompt:'请输入0.00000000001~0.01',
    limit: '[^\\d|\\.]',
    min:'0.00000000001',
    max:'0.01',
    required: true,
    dependence: 'privacyModel====DifferentPrivacy',
  },
  {
    name: 'epsilon',
    property: 'input',
    prompt:'请输入0.01~10.0',
    limit: '[^\\d|\\.]',
    min: '0.01',
    max: '10.0',
    required: true,
    dependence: 'privacyModel===DifferentPrivacy',
  },
  {
    name: 'generalization',
    property: 'select',
    value: [
      'None',
      'Low',
      'LowMedium',
      'Medium',
      'MediumHigh',
      'High',
      'Complete',
    ],
    required: true,
    dependence: 'privacyModel===DifferentPrivacy',
  },
  {
    name: 'deterministic',
    property: 'select',
    value: ['true', 'false'],
    required: true,
    dependence: 'privacyModel===DifferentPrivacy',
  },
  {
    name: 'k',
    property: 'input',
    min: '2',
    max: '1000',
    prompt: '请输入2~1000',
    limit: '[^\\d]',
    required: true,
    dependence: 'privacyModel===KAnonymity',
  },
  {
    name: 'kMapValue',
    property: 'input',
    limit: '[^\\d]',
    prompt: '请输入2~1000',
    min: '2',
    max: '1000',
    required: true,
    dependence: 'privacyModel===KAnonymity',
  },
  {
    name: 'significanceLevel',
    property: 'input',
    limit: '[^\\d|.]',
    prompt: '请输入0.0~1.0',
    min:'0.0',
    max: '1.0',
    required: true,
    dependence: 'privacyModel===KAnonymity',
  },
  {
    name: 'estimator',
    property: 'select',
    value: ['Poisson', 'Zero-truncated-Poisson'],
    required: true,
    dependence: 'privacyModel===KAnonymity',
  },
  {
    name: 'dMin',
    property: 'input',
    limit: '[^\\d|.]',
    prompt: '请输入0.0~1.0',
    min:'0.0',
    max: '1.0',
    require: true,
    dependence: 'privacyModel===KAnonymity',
  },
  {
    name: 'dMax',
    property: 'input',
    limit: '[^\\d|.]',
    prompt: '请输入0.0~1.0',
    min:'0.0',
    max: '1.0',
    required: true,
    dependence: 'privacyModel===KAnonymity',
  },
  {
    name: 'Ivalue',
    property: 'input',
    limit: '[^\\d]',
    prompt: '请输入2~1000',
    min: '2',
    max: '1000',
    required: true,
    dependence: 'privacyModel===KAnonymity',
  },
  {
    name: 'tValue',
    property: 'input',
    limit: '[^\\d|.]',
    prompt: '请输入0.000001~1.0',
    min: '0.000001',
    max: '1.0',
    required: true,
    dependence: 'privacyModel===KAnonymity',
  },
  {
    name: 'dValue',
    property: 'input',
    limit: '[^\\d|.]',
    prompt: '请输入0.000001~1000000.0',
    min: '0.000001',
    max: '1000000.0',
    required: true,
    dependence: 'privacyModel===KAnonymity',
  },
  {
    name: 'bValue',
    property: 'input',
    limit: '[^\\d|.]',
    prompt: '请输入0.000001~1000000.0',
    min: '0.000001',
    max: '1000000.0',
    required: true,
    dependence: 'privacyModel===KAnonymity',
  },
  {
    name: 'threshold1',
    property: 'input',
    limit: '[^\\d|.]',
    prompt: '请输入0.0~1.0',
    min: '0.0',
    max: '1.0',
    required: true,
    dependence: 'privacyModel===KAnonymity',
  },
  {
    name: 'threshold2',
    property: 'input',
    limit: '[^\\d|.]',
    prompt: '请输入0.0~1.0',
    min: '0.0',
    max: '1.0',
    required: true,
    dependence: 'privacyModel===KAnonymity',
  },
  {
    name: 'threshold3',
    property: 'input',
    limit: '[^\\d|.]',
    prompt: '请输入0.0~1.0',
    min: '0.0',
    max: '1.0',
    required: true,
    dependence: 'privacyModel===KAnonymity',
  },
  {
    name: 'publisherBenefit',
    property: 'input',
    limit: '[^\\d]',
    prompt: '请输入整数',
    required: true,
    dependence: false,
  },
  {
    name: 'publisherLoss',
    property: 'input',
    prompt: '请输入整数',
    limit: '[^\\d]',
    required: true,
    dependence: false,
  },
  {
    name: 'adversaryCost',
    property: 'input',
    prompt: '请输入整数',
    limit: '[^\\d]',
    required: true,
    dependence: false,
  },
  {
    name: 'adversaryGain',
    property: 'input',
    prompt: '请输入整数',
    limit: '[^\\d]',
    required: true,
    dependence: false,
  },
  {
    name: 'limit',
    property: 'input',
    prompt: '请输入整数',
    limit: '[^\\d]',
    min: '0',
    max: '100',
    required: true,
    dependence: false,
  },
  {
    name: 'isPracticalMonotonicitu',
    property: 'select',
    value: ['true', 'false'],
    required: true,
    dependence: false,
  },
  {
    name: 'isEnable',
    property: 'select',
    value: ['true', 'false'],
    required: true,
    dependence: false,
  },
  {
    name: 'measure',
    property: 'select',
    value: [
      'AECS',
      'Discernability',
      'Height',
      'Loss',
      'Entropy',
      'Precision',
      'Ambiguity',
      'NormalizedEntropy',
      'KLDivergence',
      'PublisherPayoutJournalist',
      'EntropyBasedInformationLoss',
      'Classification',
    ],
    required: true,
    dependence: false,
  },
  {
    name: 'aggregateFun',
    property: 'select',
    value: [
      "Sum","Maximum","Arithmetric mean","Geometric mean","Rank"
    ],
    required: true,
    dependence: false
  }
];
